# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_base_joint
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_end_joint
    - finger_1_joint
    - finger_2_joint
    - finger_3_joint
    - camera_revolute
    - wheel_joint_back_left
    - wheel_joint_back_right
    - wheel_joint_front_left
    - wheel_joint_front_right
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_base_joint
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_end_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_1_joint
      - finger_2_joint
      - finger_3_joint
arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - arm_base_joint
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_end_joint
  gains:
    arm_base_joint: {p: 100.0, d: 0, i: 0.1}
    link_1_joint: {p: 100.0, d: 0, i: 0.1}
    link_2_joint: {p: 100.0, d: 0, i: 0.1}
    link_3_joint: {p: 100.0, d: 0, i: 0.1}
    link_end_joint: {p: 100.0, d: 0, i: 0.1}
gripper_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - finger_1_joint
    - finger_2_joint
    - finger_3_joint
  gains:
    finger_1_joint: {p: 100.0, d: 0, i: 0.1}
    finger_2_joint: {p: 100.0, d: 0, i: 0.1}
    finger_3_joint: {p: 100.0, d: 0, i: 0.1}
camera_controller:
  type: velocity_controllers/JointPositionController
  joint: camera_revolute
  pid: {p: 100.0, d: 0, i: 0.1}

    
